#!/usr/bin/env python3
"""Bridge Claude Code and Codex project context.

This script supports three workflows:

- Scan a tree for projects that have Claude or Codex context.
- Mirror Claude project context into Codex context.
- Mirror Codex project context into Claude context, or fill whichever side is
  missing in bidirectional mode.

Default invocation stays compatible with the old project-local use:

    python scripts/sync_agent_context.py

which syncs the current repo from Claude to Codex.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable


GENERATED_MARKER = "Generated by scripts/sync_agent_context.py"
CLAUDE_ENTRY = "CLAUDE.md"
CODEX_ENTRY = "AGENTS.md"
CLAUDE_DIR = ".claude"
CODEX_DIR = ".codex"
COMMON_HOOK_FILE = "hooks.json"
CODEX_CONFIG = "config.toml"
CODEX_README = "README.md"
PROJECT_MEMORY_INDEX = Path(CODEX_DIR) / "project-memory" / "MEMORY.md"
DEFAULT_CONFIG_FILENAME = "agent_context_sync.config.json"
DEFAULT_HOOK_EVENTS = (
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "PermissionRequest",
    "Stop",
)
EXCLUDED_CONFIG_NAMES = {
    "scheduled_tasks.lock",
    COMMON_HOOK_FILE,
    CODEX_CONFIG,
    CODEX_README,
    ".DS_Store",
    "__pycache__",
    "tmp",
    "cache",
    "log",
    "logs",
}
SCAN_PRUNE_NAMES = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "node_modules",
    "wandb",
    "outputs",
    "checkpoints",
    "model_weights",
}


@dataclass(frozen=True)
class SkillMeta:
    name: str
    description: str
    path: Path


@dataclass(frozen=True)
class ProjectState:
    root: Path
    has_git: bool
    has_claude_entry: bool
    has_claude_dir: bool
    has_codex_entry: bool
    codex_kind: str

    @property
    def has_claude(self) -> bool:
        return self.has_claude_entry or self.has_claude_dir

    @property
    def has_codex(self) -> bool:
        return self.has_codex_entry or self.codex_kind != "none"

    @property
    def status(self) -> str:
        if self.has_claude and self.has_codex:
            return "both"
        if self.has_claude:
            return "claude-only"
        if self.has_codex:
            return "codex-only"
        return "none"

    @property
    def needs_sync(self) -> bool:
        return self.status in {"claude-only", "codex-only"} or self.codex_kind == "file"


class ChangeLog:
    def __init__(self, check: bool) -> None:
        self.check = check
        self.changes: list[str] = []
        self.conflicts: list[str] = []
        self.planned_dirs: set[Path] = set()
        self.planned_backups: set[Path] = set()

    def change(self, message: str) -> None:
        self.changes.append(message)

    def conflict(self, message: str) -> None:
        self.conflicts.append(message)


def repo_root_from_script() -> Path:
    return Path.cwd()


def tool_dir() -> Path:
    return Path(__file__).resolve().parent


def default_config_path() -> Path:
    return tool_dir() / DEFAULT_CONFIG_FILENAME


def refresh_command_for(root: Path) -> str:
    script = Path(__file__).resolve()
    try:
        script_ref = script.relative_to(root.resolve())
    except ValueError:
        script_ref = script
    python = Path(sys.executable).name or "python3"
    if python == "python":
        python = "python3"
    return f"{python} {script_ref} sync . --direction bidirectional"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str, log: ChangeLog) -> None:
    old = read_text(path) if path.exists() and path.is_file() else None
    if old == content:
        return
    log.change(f"write {path}")
    if log.check:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def is_generated(path: Path) -> bool:
    return path.exists() and path.is_file() and GENERATED_MARKER in read_text(path)


def ensure_directory(path: Path, log: ChangeLog) -> None:
    if path in log.planned_dirs:
        return
    if path.is_dir():
        return
    if path.exists() or path.is_symlink():
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = path.with_name(f"{path.name}.file.backup.{timestamp}")
        if path not in log.planned_backups:
            log.change(f"backup {path} -> {backup}")
            log.planned_backups.add(path)
        if not log.check:
            path.rename(backup)
    log.change(f"mkdir {path}")
    log.planned_dirs.add(path)
    if log.check:
        return
    path.mkdir(parents=True, exist_ok=True)


def remove_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def same_file_content(a: Path, b: Path) -> bool:
    if not a.is_file() or not b.is_file():
        return False
    try:
        return a.read_bytes() == b.read_bytes()
    except OSError:
        return False


def parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    data: dict[str, str] = {}
    i = 1
    while i < len(lines):
        line = lines[i]
        if line.strip() == "---":
            break
        if ":" not in line or line.startswith((" ", "\t")):
            i += 1
            continue

        key, raw_value = line.split(":", 1)
        key = key.strip()
        value = raw_value.strip()
        if value in {">", "|"}:
            block: list[str] = []
            i += 1
            while i < len(lines):
                nested = lines[i]
                if nested.strip() == "---":
                    i -= 1
                    break
                if nested and not nested.startswith((" ", "\t")) and ":" in nested:
                    i -= 1
                    break
                block.append(nested.strip())
                i += 1
            data[key] = " ".join(part for part in block if part)
        else:
            if value.startswith('"') and value.endswith('"'):
                try:
                    value = json.loads(value)
                except json.JSONDecodeError:
                    value = value[1:-1]
            elif value.startswith("'") and value.endswith("'"):
                try:
                    value = ast.literal_eval(value)
                except (SyntaxError, ValueError):
                    value = value[1:-1]
            data[key] = value
        i += 1
    return data


def discover_skills(config_dir: Path) -> list[SkillMeta]:
    skills_root = config_dir / "skills"
    if not skills_root.is_dir():
        return []

    skills: list[SkillMeta] = []
    for skill_md in sorted(skills_root.glob("*/SKILL.md")):
        meta = parse_frontmatter(read_text(skill_md))
        name = meta.get("name") or skill_md.parent.name
        description = meta.get("description") or "No description in SKILL.md frontmatter."
        skills.append(SkillMeta(name=name, description=" ".join(description.split()), path=skill_md))
    return skills


def discover_aux_files(config_dir: Path) -> list[Path]:
    if not config_dir.is_dir():
        return []
    files: list[Path] = []
    for child in sorted(config_dir.iterdir()):
        if child.name in EXCLUDED_CONFIG_NAMES:
            continue
        if child.is_file() and child.name != "SKILL.md":
            files.append(child)
    return files


def extract_mirrored_section(text: str, source_entry: str) -> str:
    heading = f"## Mirrored {source_entry}"
    marker = text.find(heading)
    if marker < 0:
        return text.rstrip()
    lines = text[marker:].splitlines()
    body_started = False
    body: list[str] = []
    for line in lines[1:]:
        if not body_started:
            if not line.strip():
                continue
            if line.startswith("The section below is copied"):
                continue
            body_started = True
        body.append(line)
    return "\n".join(body).rstrip()


def remove_guarded_block(text: str, begin: str, end: str) -> str:
    if begin not in text or end not in text:
        return text
    start = text.index(begin)
    stop = text.index(end, start) + len(end)
    next_newline = text.find("\n", stop)
    if next_newline != -1:
        stop = next_newline + 1
    return text[:start].rstrip() + "\n\n" + text[stop:].lstrip()


def skill_index_lines(target_side: str, config_dir: Path) -> list[str]:
    skills = discover_skills(config_dir)
    if target_side == "codex":
        target_dir = CODEX_DIR
    else:
        target_dir = CLAUDE_DIR

    lines = [
        "## Project Skill Index",
        "",
        f"Project-local skills are mirrored into `{target_dir}/skills` when present.",
        f"If a request matches one of these descriptions, read `{target_dir}/skills/<name>/SKILL.md` first, then load only the referenced files needed for the task.",
        "",
    ]
    if skills:
        for skill in skills:
            lines.append(f"- `{skill.name}`: {skill.description}")
    else:
        lines.append("- No project-local skills found.")
    return lines


def aux_file_lines(target_side: str, config_dir: Path) -> list[str]:
    aux_files = discover_aux_files(config_dir)
    if not aux_files:
        return []
    target_dir = CODEX_DIR if target_side == "codex" else CLAUDE_DIR
    lines = [
        "",
        "## Auxiliary Context Files",
        "",
        f"The following top-level context files are mirrored into `{target_dir}/` for progressive disclosure:",
        "",
    ]
    for path in aux_files:
        lines.append(f"- `{target_dir}/{path.name}`")
    return lines


PROJECT_MEMORY_BEGIN = "<!-- BEGIN CODEX PROJECT MEMORY -->"
PROJECT_MEMORY_END = "<!-- END CODEX PROJECT MEMORY -->"


def project_memory_lines(root: Path) -> list[str]:
    if not (root / PROJECT_MEMORY_INDEX).exists():
        return []
    return [
        "",
        PROJECT_MEMORY_BEGIN,
        "## Codex Project Memory",
        "",
        "Codex: this project keeps project-scoped memory in `.codex/project-memory/MEMORY.md`.",
        "For tasks that depend on prior project history, recurring workflows,",
        "experiments, or user/project preferences, read that index first, then open only",
        "the referenced topic files that match the task. Treat dated status as possibly",
        "stale and verify live state before acting.",
        "",
        "Do not store secrets in project memory. Prefer durable workflow lessons and",
        "known pitfalls over transient status.",
        PROJECT_MEMORY_END,
    ]


def generate_entry(
    root: Path,
    source_side: str,
    target_side: str,
    source_text: str | None,
    source_config_dir: Path,
) -> str:
    source_entry = CLAUDE_ENTRY if source_side == "claude" else CODEX_ENTRY
    target_title = "Codex Project Entry Point" if target_side == "codex" else "Claude Project Entry Point"
    target_entry = CODEX_ENTRY if target_side == "codex" else CLAUDE_ENTRY
    source_label = "Claude Code" if source_side == "claude" else "Codex"
    target_label = "Codex" if target_side == "codex" else "Claude Code"
    target_config = CODEX_DIR if target_side == "codex" else CLAUDE_DIR
    refresh_command = refresh_command_for(root)

    clean_source_text = None
    if source_text:
        clean_source_text = extract_mirrored_section(source_text, source_entry)
        clean_source_text = remove_guarded_block(
            clean_source_text,
            PROJECT_MEMORY_BEGIN,
            PROJECT_MEMORY_END,
        ).rstrip()

    lines = [
        f"# {target_title}",
        "",
        f"<!-- {GENERATED_MARKER}; edit {source_entry} / .{source_side}/, then rerun this script. -->",
        "",
        f"{target_label} loads `{target_entry}` automatically. {source_label} loads `{source_entry}`.",
        f"This file mirrors the {source_label} project entry point so both clients start from the same repo context.",
        "",
        "Client-specific system/developer instructions still outrank mirrored project text below.",
        "For progressive disclosure, do not bulk-read every linked document; read the specific referenced file when the task needs it.",
        "",
        "To refresh the bridge after editing either side, run:",
        "",
        "```bash",
        refresh_command,
        "```",
        "",
        *skill_index_lines(target_side, source_config_dir),
        *aux_file_lines(target_side, source_config_dir),
        *project_memory_lines(root),
        "",
        f"## Mirrored {source_entry}",
        "",
    ]

    if clean_source_text:
        lines.extend(
            [
                f"The section below is copied verbatim from `{source_entry}`.",
                "",
                clean_source_text,
                "",
            ]
        )
    else:
        lines.extend(
            [
                f"No `{source_entry}` exists in this project yet.",
                f"The available project-local context has been mirrored into `{target_config}/`.",
                "",
            ]
        )
    return "\n".join(lines)


def replace_side_paths(value: Any, source_side: str, target_side: str) -> Any:
    source_dir = CLAUDE_DIR if source_side == "claude" else CODEX_DIR
    target_dir = CODEX_DIR if target_side == "codex" else CLAUDE_DIR
    if isinstance(value, str):
        return value.replace(f"{source_dir}/", f"{target_dir}/")
    if isinstance(value, list):
        return [replace_side_paths(item, source_side, target_side) for item in value]
    if isinstance(value, dict):
        return {key: replace_side_paths(item, source_side, target_side) for key, item in value.items()}
    return value


def load_hooks(config_dir: Path, source_side: str, target_side: str) -> dict[str, Any] | None:
    hooks_path = config_dir / COMMON_HOOK_FILE
    if not hooks_path.exists():
        return None
    hooks = json.loads(read_text(hooks_path))
    return replace_side_paths(hooks, source_side, target_side)


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if value is None:
        return '""'
    return toml_string(str(value))


def hook_handler_to_toml(handler: dict[str, Any]) -> str:
    fields: list[str] = [f"type = {toml_string(str(handler.get('type', 'command')))}"]
    if "command" in handler:
        fields.append(f"command = {toml_string(str(handler['command']))}")
    if "timeout" in handler:
        fields.append(f"timeout = {toml_value(handler['timeout'])}")
    elif "timeoutSec" in handler:
        fields.append(f"timeout = {toml_value(handler['timeoutSec'])}")
    if handler.get("type", "command") == "command":
        fields.append(f"async = {toml_value(bool(handler.get('async', False)))}")
    if "statusMessage" in handler:
        fields.append(f"statusMessage = {toml_string(str(handler['statusMessage']))}")
    return "{ " + ", ".join(fields) + " }"


def hook_group_to_toml(group: dict[str, Any]) -> str:
    fields: list[str] = []
    if "matcher" in group:
        fields.append(f"matcher = {toml_string(str(group['matcher']))}")
    handlers = group.get("hooks", [])
    handlers_toml = ", ".join(hook_handler_to_toml(item) for item in handlers)
    fields.append(f"hooks = [{handlers_toml}]")
    return "{ " + ", ".join(fields) + " }"


def generate_codex_config_toml(converted_hooks: dict[str, Any] | None) -> str:
    lines = [
        f"# {GENERATED_MARKER}; edit .claude/hooks.json or .codex/hooks.json, then rerun this script.",
        "# Codex-native project hook config generated from mirrored hooks.",
        "",
        "[features]",
        "hooks = true",
        "",
        "[hooks]",
    ]
    hook_events = converted_hooks.get("hooks", {}) if converted_hooks else {}
    for event in DEFAULT_HOOK_EVENTS:
        groups = hook_events.get(event, [])
        if groups:
            group_items = ", ".join(hook_group_to_toml(group) for group in groups)
            lines.append(f"{event} = [{group_items}]")
    lines.append("")
    return "\n".join(lines)


def generate_codex_readme(root: Path, mode: str) -> str:
    refresh_command = refresh_command_for(root)
    return "\n".join(
        [
            "# Codex Context Mirror",
            "",
            f"<!-- {GENERATED_MARKER}; edit CLAUDE.md / AGENTS.md or .claude/ / .codex/, then rerun this script. -->",
            "",
            "This directory is maintained by the agent context sync tool.",
            "",
            "- `../CLAUDE.md` and `../AGENTS.md` are bridged entry points.",
            "- `.claude/*` and `.codex/*` project context files are mirrored, excluding generated Codex config files and locks.",
            "- `.codex/config.toml` is generated from mirrored hook metadata when hooks exist.",
            "",
            f"Resource sync mode: `{mode}`.",
            "",
            "Refresh command:",
            "",
            "```bash",
            refresh_command,
            "```",
            "",
        ]
    )


def sync_path(
    source: Path,
    target: Path,
    mode: str,
    log: ChangeLog,
    force: bool,
    allow_replace_generated: bool = False,
) -> None:
    if not source.exists():
        return

    if mode == "symlink":
        expected = os.path.relpath(source, target.parent)
        if target.is_symlink() and os.readlink(target) == expected:
            return
        if target.exists() or target.is_symlink():
            if same_file_content(source, target):
                return
            if not (force or target.is_symlink() or allow_replace_generated or is_generated(target)):
                log.conflict(f"{target} exists; pass --force or --prefer to replace it")
                return
            log.change(f"replace {target} with symlink to {expected}")
            if log.check:
                return
            remove_path(target)
        else:
            log.change(f"create symlink {target} -> {expected}")
            if log.check:
                return
        target.parent.mkdir(parents=True, exist_ok=True)
        target.symlink_to(expected, target_is_directory=source.is_dir())
        return

    if mode == "copy":
        if target.exists() or target.is_symlink():
            if same_file_content(source, target):
                return
            if not (force or target.is_symlink() or allow_replace_generated or is_generated(target)):
                log.conflict(f"{target} exists; pass --force or --prefer to replace it")
                return
            log.change(f"replace {target} with copy of {source}")
            if log.check:
                return
            remove_path(target)
        else:
            log.change(f"copy {source} -> {target}")
            if log.check:
                return
        if source.is_dir():
            shutil.copytree(source, target, symlinks=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        return

    raise ValueError(f"unknown mode: {mode}")


def iter_mirrorable_config_items(config_dir: Path) -> Iterable[Path]:
    if not config_dir.is_dir():
        return []
    return [
        child
        for child in sorted(config_dir.iterdir())
        if child.name not in EXCLUDED_CONFIG_NAMES
    ]


def sync_config_dir(
    root: Path,
    source_side: str,
    target_side: str,
    mode: str,
    log: ChangeLog,
    force: bool,
) -> None:
    source_dir = root / (CLAUDE_DIR if source_side == "claude" else CODEX_DIR)
    target_dir = root / (CODEX_DIR if target_side == "codex" else CLAUDE_DIR)
    if not source_dir.is_dir():
        return
    items = list(iter_mirrorable_config_items(source_dir))
    if not items:
        return
    ensure_directory(target_dir, log)
    for source in items:
        sync_path(source, target_dir / source.name, mode, log, force=force)


def sync_hooks(root: Path, source_side: str, target_side: str, log: ChangeLog) -> None:
    source_dir = root / (CLAUDE_DIR if source_side == "claude" else CODEX_DIR)
    target_dir = root / (CODEX_DIR if target_side == "codex" else CLAUDE_DIR)
    if not source_dir.is_dir():
        return
    converted_hooks = load_hooks(source_dir, source_side, target_side)
    if converted_hooks is None:
        return
    ensure_directory(target_dir, log)
    hooks_json = json.dumps(converted_hooks, indent=2, ensure_ascii=False) + "\n"
    write_text(target_dir / COMMON_HOOK_FILE, hooks_json, log)
    if target_side == "codex":
        write_text(target_dir / CODEX_CONFIG, generate_codex_config_toml(converted_hooks), log)


def sync_entry_one_way(root: Path, source_side: str, target_side: str, log: ChangeLog) -> None:
    source_entry = root / (CLAUDE_ENTRY if source_side == "claude" else CODEX_ENTRY)
    target_entry = root / (CODEX_ENTRY if target_side == "codex" else CLAUDE_ENTRY)
    source_config_dir = root / (CLAUDE_DIR if source_side == "claude" else CODEX_DIR)
    source_text = read_text(source_entry) if source_entry.exists() else None
    if source_text is None and not source_config_dir.exists():
        return
    write_text(target_entry, generate_entry(root, source_side, target_side, source_text, source_config_dir), log)


def sync_one_way(
    root: Path,
    source_side: str,
    target_side: str,
    mode: str,
    log: ChangeLog,
    force: bool,
) -> None:
    sync_entry_one_way(root, source_side, target_side, log)
    sync_config_dir(root, source_side, target_side, mode, log, force=force)
    sync_hooks(root, source_side, target_side, log)
    if target_side == "codex":
        ensure_directory(root / CODEX_DIR, log)
        write_text(root / CODEX_DIR / CODEX_README, generate_codex_readme(root, mode), log)


def sync_bidirectional(root: Path, mode: str, prefer: str, log: ChangeLog, force: bool) -> None:
    claude_entry = root / CLAUDE_ENTRY
    codex_entry = root / CODEX_ENTRY
    claude_dir = root / CLAUDE_DIR
    codex_dir = root / CODEX_DIR

    if prefer == "claude" and (claude_entry.exists() or claude_dir.exists()):
        sync_one_way(root, "claude", "codex", mode, log, force=force)
        return
    if prefer == "codex" and (codex_entry.exists() or codex_dir.exists()):
        sync_one_way(root, "codex", "claude", mode, log, force=force)
        return

    if claude_entry.exists() and not codex_entry.exists():
        sync_entry_one_way(root, "claude", "codex", log)
    elif codex_entry.exists() and not claude_entry.exists():
        if is_generated(codex_entry) and claude_dir.exists():
            sync_entry_one_way(root, "claude", "codex", log)
        else:
            sync_entry_one_way(root, "codex", "claude", log)
    elif claude_entry.exists() and codex_entry.exists():
        if is_generated(codex_entry) and not is_generated(claude_entry):
            sync_entry_one_way(root, "claude", "codex", log)
        elif is_generated(claude_entry) and not is_generated(codex_entry):
            sync_entry_one_way(root, "codex", "claude", log)
        elif read_text(claude_entry) != read_text(codex_entry):
            log.conflict(f"{root}: both {CLAUDE_ENTRY} and {CODEX_ENTRY} exist and differ; pass --prefer")
    elif claude_dir.exists() and not codex_dir.exists():
        sync_entry_one_way(root, "claude", "codex", log)
    elif codex_dir.exists() and not claude_dir.exists():
        sync_entry_one_way(root, "codex", "claude", log)

    if claude_dir.exists() and not codex_dir.exists():
        sync_config_dir(root, "claude", "codex", mode, log, force=force)
        sync_hooks(root, "claude", "codex", log)
    elif codex_dir.exists() and not claude_dir.exists():
        sync_config_dir(root, "codex", "claude", mode, log, force=force)
        sync_hooks(root, "codex", "claude", log)
    elif claude_dir.exists() and codex_dir.exists():
        for source, target, source_side, target_side in [
            (claude_dir, codex_dir, "claude", "codex"),
            (codex_dir, claude_dir, "codex", "claude"),
        ]:
            for item in iter_mirrorable_config_items(source):
                target_item = target / item.name
                if target_item.exists() or target_item.is_symlink():
                    continue
                sync_path(item, target_item, mode, log, force=force)
            sync_hooks(root, source_side, target_side, log)

    if claude_dir.exists() or codex_dir.exists():
        ensure_directory(root / CODEX_DIR, log)
        write_text(root / CODEX_DIR / CODEX_README, generate_codex_readme(root, mode), log)


def project_state(root: Path) -> ProjectState:
    codex_path = root / CODEX_DIR
    if codex_path.is_dir():
        codex_kind = "dir"
    elif codex_path.exists() or codex_path.is_symlink():
        codex_kind = "file"
    else:
        codex_kind = "none"
    return ProjectState(
        root=root,
        has_git=(root / ".git").is_dir(),
        has_claude_entry=(root / CLAUDE_ENTRY).is_file(),
        has_claude_dir=(root / CLAUDE_DIR).is_dir(),
        has_codex_entry=(root / CODEX_ENTRY).is_file(),
        codex_kind=codex_kind,
    )


def scan_projects(root: Path, max_depth: int, include_config_only: bool) -> list[ProjectState]:
    root = root.resolve()
    found: list[ProjectState] = []
    for dirpath, dirnames, _filenames in os.walk(root):
        current = Path(dirpath)
        rel = current.relative_to(root)
        depth = 0 if rel == Path(".") else len(rel.parts)
        dirnames[:] = [name for name in dirnames if name not in SCAN_PRUNE_NAMES]
        if depth >= max_depth:
            dirnames[:] = []
        state = project_state(current)
        if state.has_claude or state.has_codex:
            if include_config_only or state.has_git or state.has_claude_entry or state.has_codex_entry:
                found.append(state)
    return sorted(found, key=lambda item: str(item.root))


def print_scan(states: list[ProjectState]) -> None:
    print("status       git  CLAUDE  .claude  AGENTS  .codex  path")
    print("-----------  ---  ------  -------  ------  ------  ----")
    for state in states:
        print(
            f"{state.status:<11}  "
            f"{'yes' if state.has_git else 'no ':<3}  "
            f"{'yes' if state.has_claude_entry else 'no ':<6}  "
            f"{'yes' if state.has_claude_dir else 'no ':<7}  "
            f"{'yes' if state.has_codex_entry else 'no ':<6}  "
            f"{state.codex_kind:<6}  "
            f"{state.root}"
        )


def selected_from_scan(args: argparse.Namespace) -> list[Path]:
    states = scan_projects(Path(args.from_scan), args.max_depth, args.include_config_only)
    if args.scope == "needs-sync":
        states = [state for state in states if state.needs_sync]
    elif args.scope == "claude-only":
        states = [state for state in states if state.status == "claude-only"]
    elif args.scope == "codex-only":
        states = [state for state in states if state.status == "codex-only"]
    return [state.root for state in states]


def sync_project(root: Path, args: argparse.Namespace, log: ChangeLog) -> None:
    root = root.resolve()
    if args.direction == "claude-to-codex":
        sync_one_way(root, "claude", "codex", args.mode, log, force=args.force)
    elif args.direction == "codex-to-claude":
        sync_one_way(root, "codex", "claude", args.mode, log, force=args.force)
    elif args.direction == "bidirectional":
        sync_bidirectional(root, args.mode, args.prefer, log, force=args.force)
    else:
        raise ValueError(f"unknown direction: {args.direction}")


def run_sync(args: argparse.Namespace) -> int:
    log = ChangeLog(check=args.check)
    projects = [Path(project) for project in args.projects]
    if args.from_scan:
        projects.extend(selected_from_scan(args))
    if not projects:
        projects = [repo_root_from_script()]

    seen: set[Path] = set()
    for project in projects:
        root = project.resolve()
        if root in seen:
            continue
        seen.add(root)
        sync_project(root, args, log)

    if log.conflicts:
        print("Conflicts:")
        for conflict in log.conflicts:
            print(f"  {conflict}")
    if log.changes:
        prefix = "Would synchronize" if args.check else "Synchronized"
        print(f"{prefix} agent context:")
        for change in log.changes:
            print(f"  {change}")
    elif not log.conflicts:
        print("Agent context already synchronized.")
    return 1 if (args.check and log.changes) or log.conflicts else 0


def run_scan(args: argparse.Namespace) -> int:
    states = scan_projects(Path(args.root), args.max_depth, args.include_config_only)
    print_scan(states)
    print("")
    counts: dict[str, int] = {}
    for state in states:
        counts[state.status] = counts.get(state.status, 0) + 1
    for key in ("claude-only", "codex-only", "both"):
        print(f"{key}: {counts.get(key, 0)}")
    return 0


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(read_text(path))


def config_roots(config: dict[str, Any]) -> list[str]:
    roots = config.get("scan_roots")
    if isinstance(roots, list) and roots:
        return [str(root) for root in roots]
    root = config.get("scan_root")
    if root:
        return [str(root)]
    return [str(Path.cwd())]


def filter_states(states: list[ProjectState], scope: str) -> list[ProjectState]:
    if scope == "needs-sync":
        return [state for state in states if state.needs_sync]
    if scope == "claude-only":
        return [state for state in states if state.status == "claude-only"]
    if scope == "codex-only":
        return [state for state in states if state.status == "codex-only"]
    return states


def run_heartbeat(args: argparse.Namespace) -> int:
    config_path = Path(args.config).expanduser().resolve()
    config = load_config(config_path)
    roots = args.roots or config_roots(config)
    max_depth = args.max_depth if args.max_depth is not None else int(config.get("max_depth", 3))
    scope = args.scope or str(config.get("scope", "all"))
    direction = args.direction or str(config.get("direction", "bidirectional"))
    prefer = args.prefer or str(config.get("prefer", "none"))
    mode = args.mode or str(config.get("mode", "symlink"))
    include_config_only = bool(config.get("include_config_only", False) or args.include_config_only)

    log = ChangeLog(check=args.check)
    seen: set[Path] = set()
    for root_value in roots:
        root = Path(root_value).expanduser().resolve()
        states = filter_states(scan_projects(root, max_depth, include_config_only), scope)
        for state in states:
            if state.root in seen:
                continue
            seen.add(state.root)
            sync_args = argparse.Namespace(
                direction=direction,
                mode=mode,
                prefer=prefer,
                force=args.force,
            )
            sync_project(state.root, sync_args, log)

    if log.conflicts:
        print("Conflicts:")
        for conflict in log.conflicts:
            print(f"  {conflict}")
    if log.changes:
        prefix = "Would synchronize" if args.check else "Synchronized"
        print(f"{prefix} agent context:")
        for change in log.changes:
            print(f"  {change}")
    elif not log.conflicts:
        print("Agent context already synchronized.")
    return 1 if (args.check and log.changes) or log.conflicts else 0


def add_sync_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("projects", nargs="*", help="project roots to synchronize")
    parser.add_argument(
        "--from-scan",
        help="scan this root and synchronize selected projects from the scan result",
    )
    parser.add_argument("--max-depth", type=int, default=3, help="max scan depth for --from-scan")
    parser.add_argument(
        "--scope",
        choices=("needs-sync", "claude-only", "codex-only", "all"),
        default="needs-sync",
        help="which scanned projects to synchronize",
    )
    parser.add_argument(
        "--direction",
        choices=("claude-to-codex", "codex-to-claude", "bidirectional"),
        default="claude-to-codex",
        help="synchronization direction",
    )
    parser.add_argument(
        "--prefer",
        choices=("none", "claude", "codex"),
        default="none",
        help="conflict preference in bidirectional mode",
    )
    parser.add_argument(
        "--mode",
        choices=("symlink", "copy"),
        default="symlink",
        help="how config resources mirror between .claude and .codex",
    )
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    parser.add_argument("--force", action="store_true", help="replace existing non-generated targets")
    parser.add_argument(
        "--include-config-only",
        action="store_true",
        help="include directories that only have .claude/.codex but no .git or entry file",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    scan = subparsers.add_parser("scan", help="scan for Claude/Codex project context")
    scan.add_argument("--root", default=".", help="root directory to scan")
    scan.add_argument("--max-depth", type=int, default=3, help="max directory depth")
    scan.add_argument(
        "--include-config-only",
        action="store_true",
        help="include directories that only have .claude/.codex but no .git or entry file",
    )
    scan.set_defaults(func=run_scan)

    sync = subparsers.add_parser("sync", help="synchronize project context")
    add_sync_args(sync)
    sync.set_defaults(func=run_sync)

    heartbeat = subparsers.add_parser("heartbeat", help="run config-driven scheduled sync")
    heartbeat.add_argument("roots", nargs="*", help="override scan roots from config")
    heartbeat.add_argument(
        "--config",
        default=default_config_path(),
        help="JSON config file with scan_roots and sync defaults",
    )
    heartbeat.add_argument("--max-depth", type=int, default=None, help="override config max_depth")
    heartbeat.add_argument(
        "--scope",
        choices=("needs-sync", "claude-only", "codex-only", "all"),
        default=None,
        help="override config scope",
    )
    heartbeat.add_argument(
        "--direction",
        choices=("claude-to-codex", "codex-to-claude", "bidirectional"),
        default=None,
        help="override config direction",
    )
    heartbeat.add_argument(
        "--prefer",
        choices=("none", "claude", "codex"),
        default=None,
        help="override config conflict preference",
    )
    heartbeat.add_argument(
        "--mode",
        choices=("symlink", "copy"),
        default=None,
        help="override config resource mirror mode",
    )
    heartbeat.add_argument("--check", action="store_true", help="report drift without writing")
    heartbeat.add_argument("--force", action="store_true", help="replace existing non-generated targets")
    heartbeat.add_argument(
        "--include-config-only",
        action="store_true",
        help="include directories that only have .claude/.codex but no .git or entry file",
    )
    heartbeat.set_defaults(func=run_heartbeat)
    return parser


def legacy_args(argv: list[str]) -> list[str]:
    if len(argv) == 1:
        return ["sync", str(repo_root_from_script()), "--direction", "claude-to-codex"]
    if argv[1] in {"scan", "sync", "heartbeat", "-h", "--help"}:
        return argv[1:]
    return ["sync", str(repo_root_from_script()), *argv[1:]]


def main(argv: list[str] | None = None) -> int:
    raw_argv = sys.argv if argv is None else argv
    parser = build_parser()
    args = parser.parse_args(legacy_args(raw_argv))
    if not hasattr(args, "func"):
        parser.print_help()
        return 2
    try:
        return args.func(args)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
