"""Red contracts for staged teaching-artifact and ZotLit managed-region checks."""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

# teaching-gate: fast


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures" / "teaching"
VALIDATOR = (
    ROOT
    / "skills"
    / "teaching-reconstruction"
    / "scripts"
    / "validate_teaching_artifact.py"
)


def git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        text=True,
        capture_output=True,
        check=False,
    )


def run_staged_validator(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(VALIDATOR), "--staged", "--repo", str(repo)],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


class TeachingPrecommitTests(unittest.TestCase):
    def make_repo(self) -> tempfile.TemporaryDirectory[str]:
        tmp = tempfile.TemporaryDirectory()
        repo = Path(tmp.name)
        self.assertEqual(git(repo, "init").returncode, 0)
        self.assertEqual(git(repo, "config", "user.email", "tests@example.invalid").returncode, 0)
        self.assertEqual(git(repo, "config", "user.name", "Teaching Tests").returncode, 0)
        note = repo / "note.md"
        note.write_text(
            textwrap.dedent(
                """\
                # Note

                %%zt-managed%%
                ZotLit generated bytes.
                %%/zt-managed%%

                Agent-owned section.
                """
            ),
            encoding="utf-8",
        )
        self.assertEqual(git(repo, "add", "note.md").returncode, 0)
        committed = git(repo, "commit", "-m", "initial")
        self.assertEqual(committed.returncode, 0, committed.stderr + committed.stdout)
        return tmp

    def test_staged_good_teaching_artifact_passes(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            shutil.copyfile(FIXTURES / "good_guided_session.md", repo / "teaching.md")
            self.assertEqual(git(repo, "add", "teaching.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
            self.assertIn("STAGED_VALID", result.stdout)

    def test_staged_validation_fails_closed_without_a_head_baseline(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            self.assertEqual(git(repo, "init").returncode, 0)
            shutil.copyfile(FIXTURES / "good_guided_session.md", repo / "teaching.md")
            self.assertEqual(git(repo, "add", "teaching.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0, "no-HEAD staged validation false-greened")
            self.assertIn("GIT_BASELINE_MISSING", result.stderr + result.stdout)

    def test_staged_good_compiled_artifact_passes(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            shutil.copyfile(FIXTURES / "good_artifact.md", repo / "compiled_artifact.md")
            self.assertEqual(git(repo, "add", "compiled_artifact.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
            self.assertIn("STAGED_VALID", result.stdout)

    def test_staged_invalid_teaching_artifact_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            shutil.copyfile(FIXTURES / "bad_missing_check.md", repo / "teaching.md")
            self.assertEqual(git(repo, "add", "teaching.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0, "invalid staged artifact unexpectedly passed")
            self.assertIn("MISSING_CHECK", result.stderr + result.stdout)

    def test_staged_wrong_version_marker_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            shutil.copyfile(FIXTURES / "bad_wrong_version_marker.md", repo / "teaching.md")
            self.assertEqual(git(repo, "add", "teaching.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0, "wrong-version artifact unexpectedly passed")
            self.assertIn("VERSION_MARKER_WRONG", result.stderr + result.stdout)

    def test_staged_managed_region_byte_change_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            note = repo / "note.md"
            note.write_text(
                textwrap.dedent(
                    """\
                    # Note

                    %%zt-managed%%
                    Illegally edited ZotLit generated bytes.
                    %%/zt-managed%%

                    Agent-owned section.
                    """
                ),
                encoding="utf-8",
            )
            self.assertEqual(git(repo, "add", "note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0, "managed-region edit unexpectedly passed")
            self.assertIn("MANAGED_REGION_STAGED", result.stderr + result.stdout)

    def test_staged_managed_region_move_fails_even_when_region_bytes_are_unchanged(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            note = repo / "note.md"
            note.write_text(
                textwrap.dedent(
                    """\
                    # Note

                    Agent-owned section.

                    %%zt-managed%%
                    ZotLit generated bytes.
                    %%/zt-managed%%
                    """
                ),
                encoding="utf-8",
            )
            self.assertEqual(git(repo, "add", "note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0, "moving the managed region unexpectedly passed")
            self.assertIn("MANAGED_REGION_STAGED", result.stderr + result.stdout)

    def test_staged_teaching_heading_inside_managed_region_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            shutil.copyfile(FIXTURES / "bad_managed_region_heading.md", repo / "teaching.md")
            self.assertEqual(git(repo, "add", "teaching.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0, "managed-region heading unexpectedly passed")
            self.assertIn("MANAGED_REGION_HEADING", result.stderr + result.stdout)

    def test_staged_agent_owned_change_outside_managed_region_passes(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            note = repo / "note.md"
            note.write_text(
                textwrap.dedent(
                    """\
                    # Note

                    %%zt-managed%%
                    ZotLit generated bytes.
                    %%/zt-managed%%

                    Agent-owned section with a safe teaching note.
                    """
                ),
                encoding="utf-8",
            )
            self.assertEqual(git(repo, "add", "note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
            self.assertIn("STAGED_VALID", result.stdout)

    def test_staged_new_agent_owned_content_before_managed_region_passes(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            note = repo / "note.md"
            note.write_text(
                note.read_text(encoding="utf-8").replace(
                    "# Note\n", "# Note\n\nNew Agent-owned context before the projection.\n"
                ),
                encoding="utf-8",
            )
            self.assertEqual(git(repo, "add", "note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
            self.assertIn("STAGED_VALID", result.stdout)

    def test_unmarked_teaching_heading_outside_managed_region_passes(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            note = repo / "note.md"
            note.write_text(note.read_text(encoding="utf-8") + "\n## Teaching thoughts\nSafe prose.\n", encoding="utf-8")
            self.assertEqual(git(repo, "add", "note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
            self.assertIn("STAGED_VALID", result.stdout)

    def test_staged_deletion_of_managed_region_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            self.assertEqual(git(repo, "rm", "note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("MANAGED_REGION_STAGED", result.stderr + result.stdout)

    def test_staged_addition_of_managed_region_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            added = repo / "new-note.md"
            added.write_text("# New\n\n%%zt-managed%%\nGenerated bytes.\n%%/zt-managed%%\n", encoding="utf-8")
            self.assertEqual(git(repo, "add", "new-note.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("MANAGED_REGION_STAGED", result.stderr + result.stdout)

    def test_staged_renamed_managed_region_edit_fails(self) -> None:
        with self.make_repo() as tmp:
            repo = Path(tmp)
            self.assertEqual(git(repo, "mv", "note.md", "renamed.md").returncode, 0)
            renamed = repo / "renamed.md"
            renamed.write_text(
                renamed.read_text(encoding="utf-8").replace("ZotLit generated bytes.", "Changed generated bytes."),
                encoding="utf-8",
            )
            self.assertEqual(git(repo, "add", "renamed.md").returncode, 0)
            result = run_staged_validator(repo)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("MANAGED_REGION_STAGED", result.stderr + result.stdout)


if __name__ == "__main__":
    unittest.main()
